(function(root){
  'use strict';
  const PAGES={spells:['技能资料','查名字、看消耗与射程，再核对来源。'],trainers:['职业与专精导师','保留导师副标题原文，按地点寻找职业和专业服务。'],quests:['任务向导','查看接取、交付与向导步骤；以游戏内任务状态为准。'],modifiers:['词缀与附魔','查询关联附魔及原始数值，保留资料中的未知项。'],items:['物品图标','此表提供物品 ID 与客户端图标，名称和完整属性未提供。'],maps:['地图资料','查看世界与分块的静态表摘要。'],guide:['新手阅读指南','从查技能、找导师到阅读任务地点。'],sources:['数据来源与范围','哪些数据已提供，哪些信息仍然缺失。']};
  const KINDS={properties:'随机词缀',suffixes:'随机后缀',enchants:'附魔'};
  const singular={spells:'spell',trainers:'trainer',quests:'quest',modifiers:'modifier',items:'item',maps:'map'};
  function value(v){return v===null||v===undefined?'未提供':v===''?'空字符串（源值）':typeof v==='boolean'?(v?'是':'否'):Array.isArray(v)?v.map(value).join('、'):typeof v==='object'?Object.entries(v).map(([k,x])=>`${k}: ${value(x)}`).join('\n'):String(v);}
  function plain(v){return v==null?'':typeof v==='object'?Object.values(v).map(plain).join(' '):String(v);}
  function recordKey(page,r){return page==='trainers'?`${r.map}:${r.entry}`:page==='quests'?`${r.map}:${r.id}`:page==='modifiers'?`${r.kind}:${r.id}`:page==='maps'?r.source:String(r.id);}
  function parseRoute(hash){
    let parts;try{parts=decodeURIComponent((hash||'#spell/133').replace(/^#/, '')).split('/');}catch(_){return {page:'guide',key:null};}
    const page=Object.entries(singular).find(([,s])=>s===parts[0])?.[0];
    if(page)return {page,key:parts.slice(1).join('/')||null};
    return {page:PAGES[parts[0]]?parts[0]:'guide',key:null};
  }
  function index(records,page){const fields={spells:['id','name','rank','description','range','cost','cooldown','cast','equipment','sources'],trainers:['entry','name','subtitle','map','services','points','source'],quests:['id','title','map','mainline','starters','finishers','steps','source'],modifiers:['kind','id','name','text','amount','enchants','allocation','source'],items:['id','name','icon','source'],maps:['type','source','json','table_counts']}[page];return records.map(r=>({r,key:recordKey(page,r),search:plain(fields.map(k=>r[k])).toLocaleLowerCase()}));}
  function filter(entries,query='',subtype='all',page='spells'){const tokens=query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);return entries.filter(e=>tokens.every(t=>e.search.includes(t))&&(subtype==='all'||page==='trainers'&&e.r.services.includes(subtype)||page==='modifiers'&&e.r.kind===subtype||page==='maps'&&e.r.type===subtype||page==='quests'&&(subtype==='mainline'?e.r.mainline===true:e.r.mainline===false)));}
  function paginate(entries,page=1,size=30){const pages=Math.max(1,Math.ceil(entries.length/size)),current=Math.min(pages,Math.max(1,page));return {items:entries.slice((current-1)*size,current*size),page:current,pages,total:entries.length,start:entries.length?(current-1)*size+1:0,end:Math.min(current*size,entries.length)};}
  function collections(data){const modifiers=Object.keys(KINDS).flatMap(kind=>Object.entries(data.items[kind]||{}).map(([id,r])=>({kind,id:Number(id),...r,source:`${data.items.random_source}#${kind}/${id}`})));return {spells:data.detailed.spells,trainers:data.classes.trainers,quests:data.quests.quests,modifiers,items:data.items.items,maps:data.maps.maps};}
  function iconInfo(manifest,page,r){let mapping=page==='spells'?manifest?.spells?.[r.id]:null;const key=mapping?.key||(page==='items'?manifest?.items?.[r.id]:null)||r.icon||r.original_values?.icon||r.raw?.spellbook?.icon||manifest?.fallback;const icon=manifest?.icons?.[key];if(page==='spells'&&!mapping)mapping={generic:/^(?:skill_|book$)/.test(key||''),fallback:key===manifest?.fallback,spellbook_icon:r.original_values?.icon||r.raw?.spellbook?.icon};return {key,icon,mapping,sheet:icon?manifest.sheets?.[icon.sheet]:null};}
  const api={value,plain,recordKey,parseRoute,index,filter,paginate,collections,iconInfo};root.DuskWiki=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(typeof document==='undefined')return;
  function start(){
    const $=id=>document.getElementById(id),state={page:'spells',pageNumber:1,selected:null,data:null,indices:{},fullIndex:null,fullCatalog:null,icons:null,iconFiles:new Map(),filtered:[],loadId:0,routeId:0,ready:false};
    document.documentElement.dataset.wikiState='starting';
    function el(tag,text,cls){const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;}
    function status(text,error=false){$('status').textContent=text;$('status').className=error?'error':'';$('retry').hidden=!error;}
    async function json(name,signal){const response=await fetch(new URL(`data/${name}`,document.baseURI),{signal,cache:'no-cache'});if(!response.ok)throw Error(`${name} HTTP ${response.status}`);return response.json();}
    async function bounded(task){const controller=new AbortController();let timer,expired=false;try{return await Promise.race([task(controller.signal),new Promise((_,reject)=>{timer=setTimeout(()=>{expired=true;controller.abort();reject(Error('读取超过15秒'));},15000);})]);}catch(error){controller.abort();if(expired)throw Error('读取超过15秒，请重试');throw error;}finally{clearTimeout(timer);}}
    function assetUrl(path){if(typeof path!=='string'||/^(?:\/|[a-z]+:|\.\.\/)/i.test(path))return null;const base=new URL('.',document.baseURI),url=new URL(path,base);return url.origin===base.origin&&url.pathname.startsWith(base.pathname)?url.href:null;}
    function prepareIcons(){
      state.iconFiles.clear();for(const sheet of state.icons?.sheets||[]){const url=assetUrl(sheet.url);if(!url)continue;const image=new Image();state.iconFiles.set(sheet.url,'loading');image.onload=()=>{state.iconFiles.set(sheet.url,'ready');for(const node of document.querySelectorAll('[data-icon-sheet]'))if(node.dataset.iconSheet===sheet.url)node.classList.add('has-image');};image.onerror=()=>{state.iconFiles.set(sheet.url,'failed');status('资料可查询；部分图标图片未读取，可点重新读取。',true);};image.src=url;}
    }
    function iconNode(page,r,size=36){
      const info=iconInfo(state.icons,page,r),n=el('span',null,'icon'+(size>36?' large':''));n.setAttribute('role','img');n.setAttribute('aria-label',info.icon?`${r.name||'物品'}图标${info.mapping?.generic?'（客户端通用图标）':''}`:'未提供图标');
      const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d','M5 4h14v16H5z M9 9a3 3 0 0 1 6 0c0 2-3 2-3 4 M12 16v1');svg.append(path);n.append(svg);
      if(info.icon&&info.sheet){const url=assetUrl(info.sheet.url),i=info.icon,scale=size/i.width;if(url){n.style.backgroundImage=`url("${url}")`;n.style.backgroundSize=`${info.sheet.width*scale}px ${info.sheet.height*scale}px`;n.style.backgroundPosition=`${-i.x*scale}px ${-i.y*scale}px`;n.dataset.iconSheet=info.sheet.url;if(state.iconFiles.get(info.sheet.url)==='ready')n.classList.add('has-image');}}
      return n;
    }
    function displayName(page,r){return page==='spells'?r.name:page==='trainers'?r.name:page==='quests'?r.title:page==='modifiers'?(r.name??r.text??'名称未提供'):page==='items'?`物品 #${r.id}`:r.source.replace('game-content/runtime/maps/','').replace(/\.sf(chunk|world)$/,'');}
    function recordMeta(page,r){if(page==='spells')return `#${r.id} · ${r.rank===''?'等级文字为空':r.rank|| (r.details===false?'仅索引记录':'详细技能')}${r.passive===true?' · 被动':''}`;if(page==='trainers')return `${value(r.subtitle)} · 地图 ${value(r.map)}`;if(page==='quests')return `#${r.id} · 地图 ${r.map} · ${r.mainline?'主线':'非主线'}`;if(page==='modifiers')return `${KINDS[r.kind]} · #${r.id}`;if(page==='items')return `名称与属性未提供 · ${value(r.icon)}`;return `${r.type==='SFWD'?'世界':'地图分块'} · 导航 ${value(r.table_counts?.navigation)} 行`;}
    function row(entry){const r=entry.r,button=el('button',null,'record-button'+(['spells','items'].includes(state.page)?'':' no-icon'));button.type='button';button.dataset.key=entry.key;button.setAttribute('aria-pressed',entry.key===state.selected?'true':'false');if(['spells','items'].includes(state.page))button.append(iconNode(state.page,r));const body=el('span');body.append(el('span',displayName(state.page,r),'record-name'),el('span',recordMeta(state.page,r),'record-meta'));if(state.page==='spells'&&(r.cost||r.range)){const mini=el('span',null,'record-mini');if(r.cost)mini.append(el('span',r.cost));if(r.range)mini.append(el('span',r.range));body.append(mini);}button.append(body);button.addEventListener('click',()=>navigateRecord(state.page,entry.key));const li=el('li');li.append(button);return li;}
    function renderList(){const page=paginate(state.filtered,state.pageNumber,Number($('page-size').value));state.pageNumber=page.page;$('results').replaceChildren();if(!page.total)$('results').append(el('li',state.ready?'没有匹配资料。试试名称、ID，或调整筛选条件。':'资料正在读取，请稍候。','empty-state'));for(const entry of page.items)$('results').append(row(entry));$('result-count').textContent=`${page.total.toLocaleString('zh-CN')} 条结果`;$('page-info').textContent=`${page.start}–${page.end} · ${page.page} / ${page.pages}`;$('previous').disabled=page.page<=1;$('next').disabled=page.page>=page.pages||!page.total;}
    function applyFilter(reset=true){if(!state.ready)return;if(reset)state.pageNumber=1;state.filtered=filter(state.page==='spells'&&$('full-index').checked&&state.fullIndex?state.fullIndex:state.indices[state.page]||[],$('query').value,$('filter').value,state.page);renderList();}
    function stats(pane,fields){const dl=el('dl',null,'stat-grid');for(const [label,v,wide]of fields){const item=el('div',null,'stat'+(wide?' wide':''));item.append(el('dt',label),el('dd',value(v)));dl.append(item);}pane.append(dl);}
    function points(pane,list){const ul=el('ul',null,'point-list');if(!list?.length)ul.append(el('li','地点未提供'));for(const p of list||[])ul.append(el('li',`${p.place||p.region||'地点名称未提供'} · x ${value(p.x)} / y ${value(p.y)}${p.via?' · 经由此处':''}`));pane.append(ul);}
    function actors(pane,label,records){pane.append(el('h3',label,'section-heading'));const ul=el('ul',null,'actor-list');for(const r of records||[]){const li=el('li');li.append(el('strong',`${r.name||'名称未提供'} · NPC ${value(r.entry)}`));points(li,r.points);ul.append(li);}if(!records?.length)ul.append(el('li','未提供'));pane.append(ul);}
    function sources(pane,r,extra=[]){const details=el('details',null,'sources');details.append(el('summary','资料来源与图标映射'));const ul=el('ul');for(const s of [...(r.sources||(r.source?[r.source]:[])),...extra].filter(Boolean)){const li=el('li');li.append(el('code',s));ul.append(li);}if(!ul.children.length)ul.append(el('li','来源未提供'));details.append(ul);pane.append(details);}
    function showDetail(r){
      const page=state.page,pane=$('detail');state.selected=recordKey(page,r);pane.classList.remove('is-empty');pane.replaceChildren();
      const title=el('div',null,'detail-title');if(['spells','items'].includes(page))title.append(iconNode(page,r,52));const heading=el('div');heading.append(el('h2',displayName(page,r)));const subtitle=el('div',null,'detail-subtitle');subtitle.append(el('span',recordMeta(page,r)));heading.append(subtitle);title.append(heading);pane.append(title);
      let iconExtra=[];if(['spells','items'].includes(page)){const i=iconInfo(state.icons,page,r);if(i.mapping?.generic)pane.append(el('p','此记录使用客户端通用图标，其他技能可能复用。','icon-caption'));else if(i.mapping?.fallback)pane.append(el('p','未找到专用映射，显示客户端缺省图标。','icon-caption'));iconExtra=[i.mapping?.mapping_source,i.icon?.source,i.icon?.definition_source];if(i.mapping?.spellbook_icon&&i.mapping.spellbook_icon!==i.key)iconExtra.push(`图标目录映射：${i.key}；技能书原图标：${i.mapping.spellbook_icon}。这里优先展示目录映射，未据此认定游戏运行时采用哪一个。`);}
      if(page==='spells'){
        const original=r.original_values||r.raw?.spellbook||{};pane.append(el('p',r.description??'技能说明未提供。该索引记录不代表角色可学习。','detail-description'));
        stats(pane,[['消耗',r.cost],['射程',r.range],['施法',r.cast],['冷却显示',r.cooldown],['被动',r.passive],['装备要求',r.equipment],['公共冷却（毫秒）',original.global_cooldown_ms],['独立冷却（毫秒）',original.recovery_ms],['分类冷却（毫秒）',original.category_recovery_ms],['需要站定',original.requires_stationary]]);
        pane.append(el('p','人物学习等级、具体伤害与人物成长公式未在本资料中提供。','detail-notice'));
        if(original.range_check){pane.append(el('h3','客户端射程检查','section-heading'));stats(pane,[['目标',original.range_check.target],['检查类型原值',original.range_check.type],['最小值原数组',original.range_check.minimum],['最大值原数组',original.range_check.maximum]]);}
      }else if(page==='trainers'){
        pane.append(el('p',r.subtitle||'导师副标题未提供','detail-description'));stats(pane,[['NPC ID',r.entry],['地图 ID',r.map],['服务',r.services?.map(x=>x==='class_trainer'?'职业导师':x==='profession_trainer'?'专业导师':x)],['学习等级',null]]);pane.append(el('h3','导师地点','section-heading'));points(pane,r.points);pane.append(el('p','专精名称保留导师副标题原文；资料未提供完整技能树或逐技能授课关系。','detail-notice'));
      }else if(page==='quests'){
        stats(pane,[['任务 ID',r.id],['地图 ID',r.map],['主线标记',r.mainline]]);actors(pane,'接取任务',r.starters);actors(pane,'交付任务',r.finishers);pane.append(el('h3','向导步骤','section-heading'));const ol=el('ol',null,'quest-steps');for(const step of r.steps||[]){const li=el('li');li.append(el('p',step.text||'步骤说明未提供'));if(step.item)li.append(el('p',`关联物品 #${step.item}`,'muted'));for(const source of step.sources||[]){if(source.name)li.append(el('p',source.name,'muted'));points(li,source.points);}ol.append(li);}if(!r.steps?.length)ol.append(el('li','向导步骤未提供'));pane.append(ol);
      }else if(page==='modifiers'){
        stats(pane,[['类型',KINDS[r.kind]],['记录 ID',r.id],['名称',r.name],['前缀标记',r.prefix],['说明',r.text,true],['原始 amount',r.amount]]);if(r.enchants?.length){pane.append(el('h3','关联附魔','section-heading'));const links=el('div',null,'linked-tags');for(const id of r.enchants){const button=el('button',`附魔 #${id}`);button.type='button';button.addEventListener('click',()=>navigateRecord('modifiers',`enchants:${id}`));links.append(button);}pane.append(links);}if(r.allocation)stats(pane,[['allocation 原始数组',r.allocation,true]]);pane.append(el('p','amount 与 allocation 保留原值，不能直接当作已验证的最终装备属性。','detail-notice'));
      }else if(page==='items'){stats(pane,[['物品 ID',r.id],['图标键',r.icon],['名称',r.name],['品质',r.quality],['装备等级',r.level],['属性',r.stats,true]]);pane.append(el('p','当前只有客户端图标映射，物品名称与完整装备属性未提供。','detail-notice'));}
      else{stats(pane,[['文件类型',r.type],...Object.entries(r.table_counts||{}).map(([k,n])=>[`${({navigation:'导航',collision:'碰撞',marker:'标记',image:'图像',sprite:'精灵',frame:'帧',draw:'绘制',coverage:'覆盖',chunk:'分块'})[k]||k}行数`,n])]);pane.append(el('p','这是静态客户端表摘要，不包含服务器动态障碍；导航字段的行程压缩语义仍需验证。','detail-notice'));}
      const actions=el('div',null,'detail-actions'),share=el('a','打开可分享链接');share.href=`#${singular[page]}/${encodeURIComponent(state.selected)}`;actions.append(share);pane.append(actions);sources(pane,r,iconExtra);for(const button of $('results').querySelectorAll('button'))button.setAttribute('aria-pressed',button.dataset.key===state.selected?'true':'false');
    }
    function navigateRecord(page,key){const next=`#${singular[page]}/${encodeURIComponent(key)}`;if(location.hash===next)route();else location.hash=next;}
    function readerTitle(text){$('reader').append(el('h2',text));}function readerText(text){$('reader').append(el('p',text));}function readerSection(title,text){$('reader').append(el('h3',title));readerText(text);}
    function showGuide(){
      const p=$('reader');p.replaceChildren();readerTitle('开始查询');readerText('先从你正在使用的技能、要找的导师或当前任务名字入手。这里整理的是客户端随附资料，角色是否已学会、服务器是否开放仍要在游戏内确认。');
      const ol=el('ol');for(const [text,url]of [['查技能：输入中文名字或技能 ID。默认显示有详细技能书记录的技能。','#spell/133'],['找导师：查看职业与专精导师的副标题及地点，名称按原文保留。','#trainer/451%3A600301'],['看任务：按任务名搜索，分别核对接取、交付与步骤地点。','#quests']]){const li=el('li'),a=el('a',text);a.href=url;li.append(a);ol.append(li);}p.append(ol);
      readerSection('详细技能与完整索引','详细技能记录提供说明、消耗、射程与施法文字。完整索引还包含只有名字、旧版、怪物或触发用途的记录；勾选后才加载，避免首次打开下载全部数据。图标来源见详情底部，多个技能可能共用客户端通用图标。');
      readerSection('怎样读等级与冷却','“等级 1”等文字属于技能自身的显示文字，不是人物学习等级。毫秒字段与客户端冷却显示分别保留，公共冷却、独立冷却和分类冷却不能相互替代。未提供的字段没有填成 0。');
      readerSection('职业、专精与导师','“铁卫与剑锋导师”等副标题来自任务向导。它能帮助定位对应导师，但没有提供完整职业树、每个技能的学习等级或授课列表，因此这里不会根据名称推导技能归属。');
      readerSection('任务地点怎么读','地图 ID 与地点坐标按向导原值展示，没有换算成游戏世界距离。标记“经由此处”的地点可能是入口或路过位置。任务向导不等于你角色的已接、已完成状态。');
      readerSection('词缀与物品的资料范围','词缀中的附魔 ID 可以点开查看关联记录；amount 与 allocation 是原值。物品表只有 ID 和图标映射，无法在这份资料中查询完整品质、属性或掉落列表。');
      readerSection('分享与离线部署','点击资料后，地址会变成 #spell/133 这样的链接，可复制给其他玩家。页面不需要登录。整站文件可打包后放到任意静态 HTTP 服务器，所有资源使用相对路径。');
    }
    function showSources(){
      const p=$('reader');p.replaceChildren();readerTitle('资料来自哪里');readerText('内容从暮色世界客户端资源包中提取，保留来源路径、原始标记与缺失字段。技能说明用于展示，并非服务器战斗公式或开放列表。');
      const table=el('table',null,'source-table'),head=el('thead'),tr=el('tr');for(const h of ['资料','当前记录','提供范围'])tr.append(el('th',h));head.append(tr);table.append(head);const body=el('tbody');
      for(const [name,count,scope]of [['详细技能',state.data.detailed.spells.length,'技能书文字、消耗、射程及原始冷却字段'],['职业与专业导师',state.data.classes.trainers.length,'导师名称、副标题、服务与地点'],['任务向导',state.data.quests.quests.length,'接取、交付与步骤'],['词缀与附魔',state.indices.modifiers.length,'关联 ID、原始数值'],['物品图标',state.data.items.items.length,'物品 ID 与图标键'],['地图摘要',state.data.maps.maps.length,'世界、分块与表行数']]){const row=el('tr');row.append(el('td',name),el('td',count.toLocaleString('zh-CN')),el('td',scope));body.append(row);}table.append(body);p.append(table);
      readerSection('仍然缺失的内容','人物升级经验、职业基础属性、生命与法力成长、技能学习等级、完整伤害公式与物品完整属性未在这份客户端资源中找到。我们没有用其他版本的数据补齐，也没有将缺失值写成 0。');
      readerSection('图标映射','技能先采用图标目录中明确的技能 ID 映射，再按技能书图标回退。两者不一致时，在详情的来源折叠区分别保留。这个选择是资料库展示规则，未据此认定游戏运行时采用哪一个。图集保留原始裁剪与来源；通用图标会明确标注。');
      readerSection('原始资料下载','下面的 JSON 与图标映射可独立检查。SQLite 和表格适合进一步查询，内容边界与页面一致。');const downloads=el('div',null,'download-links');for(const [label,file]of [['详细技能 JSON','data/spells-detailed.json'],['完整索引 JSON','data/spell-index.json'],['完整兼容资料 JSON','data/catalog.json'],['完整图标映射 JSON','data/icons.json'],['SQLite 数据库','downloads/resources.sqlite'],['玩家参考表格','downloads/resource-workbook.xlsx']]){const a=el('a',label);a.href=`./${file}`;a.setAttribute('download','');downloads.append(a);}p.append(downloads);
    }
    function setPage(page){
      const changed=state.page!==page;state.page=page;if(changed){$('query').value='';state.pageNumber=1;state.selected=null;}
      const [title,description]=PAGES[page];$('page-title').textContent=title;$('page-description').textContent=description;document.title=`暮色世界 Wiki · ${title}`;for(const a of document.querySelectorAll('[data-page]')){if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');}
      if(state.ready)status(`资料已读取 · ${state.data.detailed.spells.length.toLocaleString('zh-CN')} 条详细技能 · 图标来自客户端`);
      const read=['guide','sources'].includes(page);$('reader').hidden=!read;$('browser').hidden=read;if(read){if(state.ready)(page==='guide'?showGuide:showSources)();else $('reader').replaceChildren(el('p','资料正在读取，请稍候。'));return;}
      $('spell-options').hidden=page!=='spells';const options={trainers:[['class_trainer','职业导师'],['profession_trainer','专业导师']],modifiers:Object.entries(KINDS),quests:[['mainline','主线'],['other','非主线']],maps:[['SFWD','世界'],['SFCH','分块']]}[page]||[];$('filter-label').hidden=!options.length;$('filter').replaceChildren();for(const [v,label]of [['all','全部'],...options]){const option=el('option',label);option.value=v;$('filter').append(option);}$('filter').value='all';$('query').placeholder=page==='spells'?'名称、ID、说明或来源，例如：火球术 133':page==='trainers'?'例如：战士导师、铁卫、松钟镇':page==='quests'?'搜索任务名字、NPC 或地点':'搜索名称、ID 或来源';$('list-hint').textContent=page==='spells'?($('full-index').checked?'完整索引包含仅有名字的记录':'默认只列有详细技能书记录的技能'):page==='trainers'?'专精保留导师副标题原文':page==='items'?'只有 ID 与图标映射，完整属性未提供':'点击查看详情及来源';
      $('detail').classList.add('is-empty');$('detail').replaceChildren(el('h2','选择一条资料'),el('p','点击一条查询结果，查看说明、数值与地点。','muted'));applyFilter();
    }
    let indexPromise,catalogPromise;
    async function ensureIndex(){if(state.fullIndex)return state.fullIndex;if(!indexPromise)indexPromise=bounded(signal=>json('spell-index.json',signal)).then(data=>{if(!Array.isArray(data.spells))throw Error('完整索引结构不正确');const detailed=new Map(state.data.detailed.spells.map(r=>[r.id,r]));state.fullIndex=index(data.spells.map(r=>detailed.get(r.id)||r),'spells');return state.fullIndex;}).catch(error=>{indexPromise=null;throw error;});return indexPromise;}
    async function fullSpell(id){const detailed=state.data.detailed.spells.find(r=>String(r.id)===id);if(detailed)return detailed;if(!catalogPromise)catalogPromise=bounded(signal=>json('catalog.json',signal)).then(data=>{state.fullCatalog=new Map(data.spells.map(r=>[String(r.id),r]));return state.fullCatalog;}).catch(error=>{catalogPromise=null;throw error;});return (await catalogPromise).get(id);}
    async function route(){
      const owner=++state.routeId,r=parseRoute(location.hash);setPage(r.page);if(!state.ready||!r.key)return;
      let entry=state.indices[r.page]?.find(e=>e.key===r.key);
      try{
        if(r.page==='spells'&&!entry){status('正在读取完整技能索引…');await ensureIndex();if(owner!==state.routeId)return;$('full-index').checked=true;applyFilter();entry=state.fullIndex.find(e=>e.key===r.key);}
        if(!entry){$('detail').classList.remove('is-empty');$('detail').replaceChildren(el('h2','没有找到这条资料'),el('p','检查链接中的 ID，或用搜索查找。','muted'));return;}
        let record=entry.r;if(r.page==='spells'&&record.details===false){status('正在读取这条索引技能的完整资料…');record=await fullSpell(r.key)||record;if(owner!==state.routeId)return;}
        showDetail(record);const position=state.filtered.findIndex(e=>e.key===r.key);if(position>=0){state.pageNumber=Math.floor(position/Number($('page-size').value))+1;renderList();}status(`资料已读取 · ${state.data.detailed.spells.length.toLocaleString('zh-CN')} 条详细技能 · 图标来自客户端`);
      }catch(error){if(owner!==state.routeId)return;status(`资料读取失败：${error.message}。可点重新读取。`,true);}
    }
    async function load(){
      const id=++state.loadId;state.ready=false;status('正在读取资料（0 / 6）…');$('result-count').textContent='正在加载';document.documentElement.dataset.wikiState='loading';const names={detailed:'spells-detailed.json',items:'items.json',classes:'classes.json',quests:'quests.json',maps:'map-index.json',icons:'icons-ui.json'};let completed=0,failed=false;
      try{
        const loaded=await bounded(signal=>Promise.all(Object.entries(names).map(async([key,name])=>{const data=await json(name,signal);if(id===state.loadId&&!failed)status(`正在读取资料（${++completed} / 6）：${name}`);return [key,data];})));if(id!==state.loadId)return;state.data=Object.fromEntries(loaded);state.icons=state.data.icons;const all=collections(state.data),indices={};for(const [page,records]of Object.entries(all)){if(!Array.isArray(records))throw Error(`${page} 数据结构不正确`);indices[page]=index(records,page);}state.indices=indices;state.ready=true;state.fullIndex=null;indexPromise=null;catalogPromise=null;prepareIcons();$('nav-spells').textContent=all.spells.length.toLocaleString('zh-CN');status(`资料已读取 · ${all.spells.length.toLocaleString('zh-CN')} 条详细技能 · 图标来自客户端`);document.documentElement.dataset.wikiState='ready';await route();
      }catch(error){failed=true;if(id!==state.loadId)return;document.documentElement.dataset.wikiState='failed';status(`资料读取失败：${error.message}。确认站点数据完整后，点重新读取。`,true);$('result-count').textContent='资料尚未读取';}
    }
    $('search-form').addEventListener('submit',e=>{e.preventDefault();applyFilter();});let queryTimer;$('query').addEventListener('input',()=>{clearTimeout(queryTimer);queryTimer=setTimeout(()=>applyFilter(),150);});$('filter').addEventListener('change',()=>applyFilter());$('page-size').addEventListener('change',()=>applyFilter());$('previous').addEventListener('click',()=>{state.pageNumber--;renderList();});$('next').addEventListener('click',()=>{state.pageNumber++;renderList();});
    $('full-index').addEventListener('change',async()=>{if(!state.ready)return;const checked=$('full-index').checked;if(!checked){applyFilter();$('list-hint').textContent='默认只列有详细技能书记录的技能';return;}$('full-index').disabled=true;status('正在读取完整技能索引，首次打开才需要下载…');try{await ensureIndex();if($('full-index').checked&&state.page==='spells'){applyFilter();$('list-hint').textContent='完整索引包含仅有名字的记录';}status(`完整索引已读取 · ${state.fullIndex.length.toLocaleString('zh-CN')} 个技能 ID`);}catch(error){$('full-index').checked=false;status(`完整索引读取失败：${error.message}。可点重新读取。`,true);}finally{$('full-index').disabled=false;}});
    $('retry').addEventListener('click',load);window.addEventListener('hashchange',route);api.retry=load;api.diagnostic=()=>({ready:state.ready,page:state.page,selected:state.selected,detailed:state.data?.detailed.spells.length||0,indexLoaded:!!state.fullIndex,results:state.filtered.length});setPage(parseRoute(location.hash).page);load();
  }
  let started=false;function boot(){if(started)return;started=true;try{start();}catch(error){document.documentElement.dataset.wikiState='failed';const s=document.getElementById('status');if(s){s.textContent=`资料库初始化失败：${error.message}。请重新加载页面。`;s.className='error';}const retry=document.getElementById('retry');if(retry)retry.hidden=false;}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})(globalThis);
